stages:
  - build
  - test

variables:
  FLASK_APP: app.py
  REACT_APP_NAME: frontend
  DOCKER_IMAGE: etulab.univ-amu.fr:5005/sae-s5.a.01-2024/sae-s5.a.01-2024-sujet03:s5a01-ae2i

Build_Image:
  stage: build
  image: docker:edge-git
  services:
    - docker:dind
  before_script:
    - apk update
    - apk add curl
    - echo "$CI_ETULAB_PROJECT_REGISTRY_TOKEN" | docker login etulab.univ-amu.fr:5005/sae-s5.a.01-2024/sae-s5.a.01-2024-sujet03:s5a01-ae2i -u "$CI_ETULAB_REGISTRY_USER" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

Frontend_Test:
  stage: test
  image: node:14
  needs: ["Build_Image"]
  before_script:
    - cd frontend
    - npm install
    - npm install --save-dev @types/react postcss-selector-parser typescript
    - npm audit fix
  script:
    - npm test -- --passWithNoTests

Backend_Test:
  stage: test
  image: python:3.9
  needs: ["Build_Image"]
  before_script:
    - cd app
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - echo ""

Code_Review:
  stage: test
  image: etulab.univ-amu.fr:5005/sae-s5.a.01-2024/sae-s5.a.01-2024-sujet03:s5a01-ae2i
  script:
    - pip install flake8
    - flake8 app/ --max-line-length=200